### ISSUE TITLE
A* - incorrect message

### ISSUE THREAD

**Issue by debitCredit** [ss892714028/Maze-PathFinder-Visualization-Python#2]
When using A* algo, there is an message that the destination cannot be reached even though it was successful.

![image](https://user-images.githubusercontent.com/771070/108353031-f2cf7b80-71e7-11eb-9a3d-7f21615a9e47.png)

**Comment by ss892714028** [comment]
The failed message was still printing despite reaching the destiny. Thank you for fixing it :D Merged!
